### ISSUE TITLE
Why using Aura?

### ISSUE THREAD

**Issue by tdelabro** [aleph-zero-foundation/aleph-node#3]
https://github.com/aleph-zero-foundation/aleph-node/blob/f2e4f18b3b7d995326d83302299b0f64a855f966/bin/node/src/service.rs#L158

I'm under the impression that even having your own BFT consensus algorithm you are still using Aura, here `sc_consensus_aura::import_queue`.

Is it possible to have an explanation for this? What are the alternatives and why you did this implementation choice? Does it matter at all?

**Comment by mike1729** [comment]
In substrate there is decoupling of consensus into block production and block finalization ([docs](https://docs.substrate.io/fundamentals/consensus/#finalization-and-forks)). We use `Aura` for block production and `AlephBFT` for block finalization.

**Comment by tdelabro** [comment]
Ok so `AlephBFT` replaces `GRANDPA`. Thank you!
